<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search ab_admin
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["ab_admin/new", "Create ab_admin"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "ab_admin/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldUserid" class="col-sm-2 control-label">UserId</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["userId", "type" => "number", "class" => "form-control", "id" => "fieldUserid"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUsername" class="col-sm-2 control-label">Username</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["username", "size" => 30, "class" => "form-control", "id" => "fieldUsername"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPassword" class="col-sm-2 control-label">Password</label>
    <div class="col-sm-10">
        <?php echo $this->tag->selectStatic(["password", [], "class" => "form-control", "id" => "fieldPassword"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEncrypt" class="col-sm-2 control-label">Encrypt</label>
    <div class="col-sm-10">
        <?php echo $this->tag->selectStatic(["encrypt", [], "class" => "form-control", "id" => "fieldEncrypt"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldRealname" class="col-sm-2 control-label">Realname</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["realname", "size" => 30, "class" => "form-control", "id" => "fieldRealname"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLastloginip" class="col-sm-2 control-label">Lastloginip</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["lastloginip", "size" => 30, "class" => "form-control", "id" => "fieldLastloginip"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLastlogintime" class="col-sm-2 control-label">Lastlogintime</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["lastlogintime", "type" => "number", "class" => "form-control", "id" => "fieldLastlogintime"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEmail" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["email", "size" => 30, "class" => "form-control", "id" => "fieldEmail"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
