<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["ab_admin/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["ab_admin/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>UserId</th>
            <th>Username</th>
            <th>Password</th>
            <th>Encrypt</th>
            <th>Realname</th>
            <th>Lastloginip</th>
            <th>Lastlogintime</th>
            <th>Email</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $ab_admin): ?>
            <tr>
                <td><?php echo $ab_admin->userId ?></td>
            <td><?php echo $ab_admin->username ?></td>
            <td><?php echo $ab_admin->password ?></td>
            <td><?php echo $ab_admin->encrypt ?></td>
            <td><?php echo $ab_admin->realname ?></td>
            <td><?php echo $ab_admin->lastloginip ?></td>
            <td><?php echo $ab_admin->lastlogintime ?></td>
            <td><?php echo $ab_admin->email ?></td>

                <td><?php echo $this->tag->linkTo(["ab_admin/edit/" . $ab_admin->userId, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["ab_admin/delete/" . $ab_admin->userId, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("ab_admin/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("ab_admin/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("ab_admin/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("ab_admin/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
