<div class="page-header">
恭喜你，已成功为你生成页面!
</div>
<table class="bordered">
<thead>
    <tr>
        <th>标题1</th>
        <th>标题2</th>
        <th>标题3</th>
        <th>标题4</th>
        <th>标题5</th>
        <th>标题6</th>
    </tr>
</thead>
<tbody>
    <?php for($i=0;$i<20;++$i):?>
<tr>
    <td>数据项0001</td>
    <td>数据项0002</td>
    <td>数据项0003</td>
    <td>数据项0004</td>
    <td>数据项0005</td>
    <td>数据项0006</td>
</tr>
    <?php endfor;?>
    </tbody>
</table>
