<div class="page-header">
    <div class="page-title">
        <span>用户管理</span>
        >
        <span>新建用户</span>
    </div>
</div>

<div class="page-body">

<form action="/member/create" method="post" autocomplete="off" class="aligned">

    <div class="form-group">
        <label for="fieldMobile" class="control-label">手机号</label>
        <div>
            <?php 
            echo $this->tag->textField(["mobile","size"=>30,"class"=>"form-control","id"=>"fieldMobile"]);
            ?>
        </div>
    </div>

    <div class="form-group">
        <label for="fieldEmail" class="control-label">邮箱</label>
        <div>
            <?php 
            echo $this->tag->textField(["email","size"=>30,"class"=>"form-control","id"=>"fieldEmail"]);
            ?>
        </div>
    </div>

    <div class="form-group">
        <label for="fieldAvatar" class="control-label">头像上传</label>
        <div class="upload-area">
            <img src="/img/presel.png" alt="" id="preview"/>
            <input type="file" name="upctrl" id="upctrl" onchange="uploadImg(this)"/>
            <input type="hidden" name="avatar" id="avatar">
        </div>
    </div>

    <div class="form-group">
        <label for="fieldNickname" class="control-label">昵称</label>
        <div>
            <?php 
            echo $this->tag->textField(["nickname","size"=>30]);
            ?>
        </div>
    </div>

    <div class="form-group">
        <label for="fieldLoginip" class="control-label">密码</label>
        <div>
            <?php 
            echo $this->tag->passwordField(["password","size"=>30]);
            ?>
        </div>
    </div>

    <div class="form-group">
        <label for="fieldRegistertime" class="control-label">重复密码</label>
        <div>
            <?php
            echo $this->tag->passwordField(["confirm","size"=>30]);
            ?>
        </div>
    </div>


    <div class="form-group">
        <button class="primary" type="submit">提交</button>
    </div>

</form>
</div>
