<div class="bread">
<a href="">会员管理</a>
<em>&#47;</em>
<span>会员中心</span>
<div class="button-group"><a href="/member/new">新建</a><a href="/member/index">返回</a></div>
</div>
<div class="page-header">
        <form method="get">
            关键字：<input type="text" name="keywords"/>
            <button type="submit" class="button primary">查询</button>
        </form>
</div>
    <table class="bordered no-padding">
        <thead>
            <tr>
                <th>编号</th>
                <th>手机</th>
                <th>邮箱</th>
                <th>头像</th>
                <th>昵称</th>
                <th>最近登录</th>
                <th>登录IP</th>
                <th>注册时间</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
        <?php if($page->items):?>
        <?php foreach($page->items as $member):?>
            <tr>
                <td class="align-right"><?=$member->memberId;?></td>
                <td class="align-center"><?=$member->mobile;?></td>
                <td class="align-left"><?=$member->email ;?></td>
                <td class="square-thumb-small">
                    <img src="/upload/avatar.jpg" />
                </td>
                <td class="align-left"><?=$member->nickname ;?></td>
                <td class="align-center"><?php if($member->lastLogin) echo date('Y.m.d H:i:s',$member->lastLogin);?></td>
                <td class="align-center"><?=$member->loginIp ;?></td>
                <td class="align-center"><?=date('Y.m.d H:i:s',$member->registerTime);?></td>
                <td style="text-align:center;">
                    <a href="/member/edit/<?=$member->memberId?>" class="small-button edit">编辑</a>
                    <a href="/member/delete/<?=$member->memberId?>" class="small-button delete">删除</a>
                </td>
            </tr>
        <?php endforeach; ?>
        <?php endif;?>
        </tbody>
    </table>
<div class="page-bar">
    <div class="pagination">
        <?=$this->tag->linkTo("member/search", "首页") ;?>
        <?=$this->tag->linkTo("member/search?page=".$page->before,"上一页");?>
        <span>
            <?php echo $page->current,"/",$page->total_pages;?>
        </span>
        <?=$this->tag->linkTo("member/search?page=".$page->next, "下一页") ;?>
        <?=$this->tag->linkTo("member/search?page=".$page->last, "尾页") ;?>
    </div>
</div>
